apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: feedback
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/jenkins"