name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      env:
        DOCKER_USER: ${{ sectrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ sectrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: |
        docker-compose up --build
    - run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: |
        docker push
